version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=orderManager
    ports:
      - "5432:5432"
#    volumes:
#      - postgresDatabase:/var/lib/postgresql/data
    
volumes:
  postgresDatabase: